# Comprehensive mapping of MX record patterns to provider names
MX_PROVIDER_MAPPING = {
    'google.com': 'Gmail',
    'outlook.com': 'Office365',
    'protection.outlook.com': 'Office365',
    'aol.com': 'Aol',
    'yahoodns.net': 'Yahoo',
    'secureserver.net': 'GoDaddy',
    'emailsrvr.com': 'Rackspace',
    'qq.com': 'QQ',
    'netease.com': 'Netease',
    '163.com': 'Netease',
    '126.com': 'Netease',
    'aliyun.com': 'Aliyun',
    'sina.com': 'Sina',
    'sina.cn': 'Sina',
    '21cn.com': '21cn',
    '263.net': '263',
    'hinet.net': 'Hinet',
    'hibox.hinet.net': 'Hibox',
    'privateemail.com': 'NameCheap',
    'networksolutions.com': 'NetworkSolutions',
    'messagelabs.com': 'MessageLabs',
    'mimecast.com': 'Mimecast',
    'pphosted.com': 'Proofpoint',
    'protonmail.ch': 'Protonmail',
    'ovh.net': 'OVH',
    'naver.com': 'Naver',
    'nifty.com': 'Nifty',
    'ocn.ad.jp': 'OCN',
    'one.com': 'One.com',
    'nominalia.com': 'Nominalia',
    'netnavigator.com': 'Netnavigator',
    'mweb.co.za': 'Mweb',
    'mycloudmailbox.com': 'MyCloudMailbox',
    'sherwebcloud.com': 'SherwebCloud',

    # Generic Webmail / Hosting Panels
    'zimbra': 'Zimbra',
    'roundcube': 'Roundcube',
    'webmail': 'Webmail',
    'cpanel': 'Webmail',
    'plesk': 'Webmail',
    'directadmin': 'Webmail',
    'mailhost': 'Webmail',
}
