# Comprehensive mapping of MX record patterns to provider names
# The order is extremely important: more specific patterns MUST come before generic ones.
MX_PROVIDER_MAPPING = {
    # --- Branded Infrastructure & Security (Specific) ---
    'messagelabs': 'MessageLabs',
    'mimecast': 'Mimecast',
    'pphosted': 'Proofpoint',
    'barracuda': 'Barracuda',
    'sophos': 'Sophos',
    'trendmicro': 'TrendMicro',

    # --- Regional & Branded ISPs (Specific) ---
    'comcast': 'Comcast',
    'charter': 'Charter',
    'cox.net': 'Cox',
    'sky.com': 'Sky',
    'bt.prod.cloud.openwave.ai': 'BT',
    'virginmedia': 'VirginMedia',
    'talktalk': 'TalkTalk',
    'earthlink': 'Earthlink',
    'windstream': 'Windstream',
    'orange.fr': 'Orange',
    'wanadoo.fr': 'Orange',
    'free.fr': 'Free.fr',
    'libero.it': 'Libero',
    'virgilio.it': 'Virgilio',
    'tiscali.it': 'Tiscali',
    'seznam.cz': 'Seznam',
    't-online.de': 'T-online',
    'swisscom': 'Swisscom',
    'bluenet.ch': 'Bluewin',
    'post.ch': 'SwissPost',
    'biglobe.ne.jp': 'Biglobe',
    'so-net.ne.jp': 'So-net',
    'rakuten': 'Rakuten',
    'uol.com.br': 'UOL',
    'bol.com.br': 'UOL',
    'terra.com.br': 'Terra',
    'telstra': 'Telstra',
    'optusnet': 'Optus',
    'rogers.com': 'Rogers',
    'shaw.ca': 'Shaw',

    # --- Specific Hosting Providers ---
    'secureserver.net': 'GoDaddy',
    'emailsrvr.com': 'Rackspace',
    '1and1': 'IONOS',
    'hostgator': 'HostGator',
    'bluehost': 'Bluehost',
    'siteground': 'SiteGround',
    'privateemail.com': 'NameCheap',
    'networksolutions': 'NetworkSolutions',
    'hinet.net': 'Hinet',
    'hibox': 'Hibox',
    'nominalia': 'Nominalia',
    'nifty.com': 'Nifty',
    'ocn.ad.jp': 'OCN',
    'netnavigator': 'Netnavigator',
    'mweb.co.za': 'Mweb',
    'mycloudmailbox': 'MyCloudMailbox',
    'sherwebcloud': 'SherwebCloud',
    'ovh.net': 'OVH',
    'one.com': 'One.com',

    # --- Major Global Providers (Generic/Infrastructure) ---
    'google': 'Gmail',
    'icloud': 'Apple',
    'apple.com': 'Apple',
    'protection.outlook.com': 'Office365',
    'eo.outlook.com': 'Office365',
    'outlook.com': 'Office365',
    'aol': 'Aol',
    'yahoodns': 'Yahoo',
    'yahoomail': 'Yahoo',
    'protonmail': 'Protonmail',
    'zoho': 'Zoho',
    'yandex': 'Yandex',
    'mail.ru': 'Mail.ru',
    'fastmail': 'Fastmail',
    'messagingengine': 'Fastmail',
    'gmx': 'GMX',
    'web.de': 'Web.de',
    'mail.com': 'Mail.com',

    # --- Chinese Providers ---
    'qq.com': 'QQ',
    'netease': 'Netease',
    '163.com': 'Netease',
    '126.com': 'Netease',
    'aliyun': 'Aliyun',
    'sina': 'Sina',
    '21cn': '21cn',
    '263.net': '263',
    'hanmail': 'Hanmail',
    'daum': 'Daum',
    'naver.com': 'Naver',

    # --- Generic Webmail / Hosting Panels ---
    'zimbra': 'Zimbra',
    'roundcube': 'Roundcube',
    'webmail': 'Webmail',
    'cpanel': 'Webmail',
    'plesk': 'Webmail',
    'directadmin': 'Webmail',
    'mailhost': 'Webmail',
}
